ARGV = []
TRUE = true
FALSE = false
STDOUT = IO.new
STDIN = IO.new
STDERR = IO.new
ENV = {}
NIL = nil
VERSION = ''
RUBY_PATCHLEVEL = 123
RUBY_COPYRIGHT = 'ruby - Copyright (C) 1993-2009 Yukihiro Matsumoto'
TOPLEVEL_BINDING = Binding.new
RUBY_VERSION = '1.8.7'
RUBY_PLATFORM = ''
PLATFORM = ''
