embed_assets: off
package_assets: on

javascripts:
  common:
    - public/javascripts/jquery.js
    - public/javascripts/jquery-ui.js
    - public/javascripts/jquery-ui-timepicker-addon.js
 #   - public/javascripts/jquery-rails.js
    - public/javascripts/application.js
    - public/javascripts/jquery.multiselect.js
    - public/javascripts/jquery.multiselect.filter.js
    - public/javascripts/active_scaffold/default/*.js
   
stylesheets:
  common:
    - public/stylesheets/active_scaffold/default/stylesheet.css
    - public/stylesheets/active_scaffold/default/stylesheet-ie.css
    - public/stylesheets/jquery*.css
    - public/stylesheets/scaffold.css
    - public/stylesheets/project_style_overrides.css
    - public/stylesheets/theme-*.css
    

