embed_assets: off
package_assets: on

javascripts:
  common:
    - public/javascripts/jquery.js
    - public/javascripts/jquery-ui.js
    - public/javascripts/jquery-ui-timepicker-addon.js
    - public/javascripts/application.js
    - public/javascripts/active_scaffold/default/*.js
   
stylesheets:
  common:
    - public/stylesheets/active_scaffold/default/*.css
    - public/stylesheets/*.css
    - public/stylesheets/jquery*.css

