# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

# coding: utf-8

Bloodtype.delete_all
Bloodtype.create(:abo => 'A', :rh => 'neg', :comment => '', :full => 'A neg')
Bloodtype.create(:abo => 'A', :rh => '+', :comment => '', :full => 'A+')
Bloodtype.create(:abo => 'A', :rh => ' Rh?', :comment => 'type A, unknown Rh', :full => 'A')
Bloodtype.create(:abo => 'B', :rh => 'neg', :comment => '', :full => 'B neg')
Bloodtype.create(:abo => 'B', :rh => '+', :comment => '', :full => 'B+')
Bloodtype.create(:abo => 'B', :rh => ' Rh?', :comment => 'type B, unknown Rh', :full => 'B')
Bloodtype.create(:abo => 'O', :rh => 'neg', :comment => '', :full => 'O neg')
Bloodtype.create(:abo => 'O', :rh => '+', :comment => '', :full => 'O+')
Bloodtype.create(:abo => 'O', :rh => ' Rh?', :comment => 'type O, unknown Rh', :full => 'O')
Bloodtype.create(:abo => '?ABO', :rh => '+', :comment => 'unknown ABO; Rh+', :full => 'something +')
Bloodtype.create(:abo => '?ABO', :rh => 'neg', :comment => 'unknown ABO; Rh neg', :full => 'something neg')
Bloodtype.create(:abo => 'AB', :rh => ' Rh?', :comment => 'type AB, unknown Rh', :full => 'AB')
Bloodtype.create(:abo => 'AB', :rh => '+', :comment => '', :full => 'AB+')
Bloodtype.create(:abo => 'AB', :rh => 'neg', :comment => '', :full => 'AB neg')
Bloodtype.create(:abo => '', :rh => '', :comment => 'unknown', :full => '')
Bloodtype.create(:abo => 'Z', :rh => 'Z', :comment => 'Z', :full => 'Z')
Bloodtype.create(:abo => 'X', :rh => 'X', :comment => 'X', :full => 'X')

City.delete_all
City.create(:name => 'Jos', :state => 'Plateau', :country => 'NG', :latitude => 9.917, :longitude => 8.9)
City.create(:name => 'Enugu', :state => 'Abia', :country => 'NG', :latitude => 6.43333, :longitude => 7.48333)
City.create(:name => 'Aba', :state => 'Abia', :country => 'NG', :latitude => 5.11667, :longitude => 7.36667)
City.create(:name => 'Egbe', :state => 'Kogi', :country => 'NG', :latitude => 8.21667, :longitude => 5.51667)
City.create(:name => 'Igbaja', :state => 'Kwara', :country => 'NG', :latitude => 8.38333, :longitude => 4.88333)
City.create(:name => 'Ilorin', :state => 'Kwara', :country => 'NG', :latitude => 8.48, :longitude => 4.55)
City.create(:name => 'Kaiama', :state => 'Kwara', :country => 'NG', :latitude => 9.6225, :longitude => 6.3)
City.create(:name => 'Abuja', :state => 'Federal Capital Territory', :country => 'NG', :latitude => 9.25, :longitude => 7)
City.create(:name => 'Gure', :state => 'Kaduna', :country => 'NG', :latitude => 10.2369, :longitude => 8.4)
City.create(:name => 'Kagoro', :state => 'Kaduna', :country => 'NG', :latitude => 9.6, :longitude => 8.3833)
City.create(:name => 'Adunu', :state => 'Kaduna', :country => 'NG', :latitude => 9.58333, :longitude => 7.15)
City.create(:name => 'Samaru', :state => 'Kaduna', :country => 'NG', :latitude => 9.72, :longitude => 8.4)
City.create(:name => 'Minna', :state => 'Niger', :country => 'NG', :latitude => 9.6139, :longitude => 6.5569)
City.create(:name => 'Ningi', :state => 'Bauchi', :country => 'NG', :latitude => 9.56968, :longitude => 11.077)
City.create(:name => 'Billiri', :state => 'Gombe', :country => 'NG', :latitude => 9.86472, :longitude => 11.2253)
City.create(:name => 'Kano', :state => 'Kano', :country => 'NG', :latitude => 11.9964, :longitude => 8.51667)
City.create(:name => 'Tofa', :state => 'Kano', :country => 'NG', :latitude => 12.0133, :longitude => 8.75)
City.create(:name => 'Miango', :state => 'Plateau', :country => 'NG', :latitude => 9.853, :longitude => 8.696)
City.create(:name => 'Gyero', :state => 'Plateau', :country => 'NG', :latitude => 9.8162, :longitude => 8.8184)
City.create(:name => 'unspecified', :state => '', :country => '??', :latitude => '', :longitude => '')

ContactType.delete_all
ContactType.create(:code => 1, :description => 'on field')
ContactType.create(:code => 4, :description => 'parent')
ContactType.create(:code => 6, :description => 'friend')
ContactType.create(:code => 5, :description => 'sibling')
ContactType.create(:code => 3, :description => 'spouse')
ContactType.create(:code => 9, :description => 'other')
ContactType.create(:code => 2, :description => 'home country')
ContactType.create(:code => 0, :description => 'unspecified')

Country.delete_all
Country.create(:code => 'AD', :name => 'Andorra', :nationality => 'Andorran', :include_in_selection => 0)
Country.create(:code => 'AE', :name => 'United Arab Emirates', :nationality => '', :include_in_selection => 0)
Country.create(:code => 'AF', :name => 'Afghanistan', :nationality => 'Afghan', :include_in_selection => 0)
Country.create(:code => 'AG', :name => 'Antigua and Barbuda', :nationality => 'Antiguan', :include_in_selection => 0)
Country.create(:code => 'AI', :name => 'Anguilla', :nationality => 'Anguillan', :include_in_selection => 0)
Country.create(:code => 'AL', :name => 'Albania', :nationality => 'Albanian', :include_in_selection => 0)
Country.create(:code => 'AM', :name => 'Armenia', :nationality => 'Armenian', :include_in_selection => 0)
Country.create(:code => 'AN', :name => 'Netherlands Antilles', :nationality => 'Dutch Antillesian', :include_in_selection => 0)
Country.create(:code => 'AO', :name => 'Angola', :nationality => 'Angolan', :include_in_selection => 0)
Country.create(:code => 'AQ', :name => 'Antarctica', :nationality => 'Antarctica', :include_in_selection => 0)
Country.create(:code => 'AR', :name => 'Argentina', :nationality => 'Argentine', :include_in_selection => 1)
Country.create(:code => 'AS', :name => 'American Samoa', :nationality => 'American Samoan', :include_in_selection => 0)
Country.create(:code => 'AT', :name => 'Austria', :nationality => 'Austrian', :include_in_selection => 1)
Country.create(:code => 'AU', :name => 'Australia', :nationality => 'Australian', :include_in_selection => 1)
Country.create(:code => 'AW', :name => 'Aruba', :nationality => 'Aruban', :include_in_selection => 0)
Country.create(:code => 'AX', :name => 'Åland Islands', :nationality => 'Åland Islands'.force_encoding('UTF-8'), :include_in_selection => 0)
Country.create(:code => 'AZ', :name => 'Azerbaijan', :nationality => 'Azerbaijanian', :include_in_selection => 0)
Country.create(:code => 'BA', :name => 'Bosnia and Herzegovina', :nationality => 'Bosnian/Herzegovinan', :include_in_selection => 0)
Country.create(:code => 'BB', :name => 'Barbados', :nationality => 'Barbadian', :include_in_selection => 0)
Country.create(:code => 'BD', :name => 'Bangladesh', :nationality => 'Bangladeshi', :include_in_selection => 0)
Country.create(:code => 'BE', :name => 'Belgium', :nationality => 'Belgian', :include_in_selection => 1)
Country.create(:code => 'BF', :name => 'Burkina Faso', :nationality => 'Burkinabe', :include_in_selection => 0)
Country.create(:code => 'BG', :name => 'Bulgaria', :nationality => 'Bulgarian', :include_in_selection => 0)
Country.create(:code => 'BH', :name => 'Bahrain', :nationality => 'Bahraini', :include_in_selection => 0)
Country.create(:code => 'BI', :name => 'Burundi', :nationality => 'Burundian', :include_in_selection => 0)
Country.create(:code => 'BJ', :name => 'Benin', :nationality => 'Beninois', :include_in_selection => 0)
Country.create(:code => 'BM', :name => 'Bermuda', :nationality => 'Bermudian', :include_in_selection => 0)
Country.create(:code => 'BN', :name => 'Brunei Darussalam', :nationality => 'Bruneian', :include_in_selection => 0)
Country.create(:code => 'BO', :name => 'Bolivia', :nationality => 'Bolivian', :include_in_selection => 1)
Country.create(:code => 'BR', :name => 'Brazil', :nationality => 'Brazilian', :include_in_selection => 1)
Country.create(:code => 'BS', :name => 'Bahamas', :nationality => 'Bahamian', :include_in_selection => 0)
Country.create(:code => 'BT', :name => 'Bhutan', :nationality => 'Bhutanese', :include_in_selection => 0)
Country.create(:code => 'BV', :name => 'Bouvet Island', :nationality => 'Bouvet Islander', :include_in_selection => 0)
Country.create(:code => 'BW', :name => 'Botswana', :nationality => 'Botswanan', :include_in_selection => 0)
Country.create(:code => 'BY', :name => 'Belarus', :nationality => 'Belarusian', :include_in_selection => 0)
Country.create(:code => 'BZ', :name => 'Belize', :nationality => 'Belizean', :include_in_selection => 0)
Country.create(:code => 'CA', :name => 'Canada', :nationality => 'Canadian', :include_in_selection => 1)
Country.create(:code => 'CC', :name => 'Cocos (Keeling) Islands', :nationality => 'Cocos Island', :include_in_selection => 0)
Country.create(:code => 'CD', :name => 'Congo, Democratic Republic', :nationality => 'Congolese', :include_in_selection => 0)
Country.create(:code => 'CF', :name => 'Central African Republic', :nationality => 'Central African', :include_in_selection => 0)
Country.create(:code => 'CG', :name => 'Congo', :nationality => 'Congolese', :include_in_selection => 0)
Country.create(:code => 'CH', :name => 'Switzerland', :nationality => 'Swiss', :include_in_selection => 1)
Country.create(:code => 'CK', :name => 'Cook Islands', :nationality => 'Cook Island', :include_in_selection => 0)
Country.create(:code => 'CL', :name => 'Chile', :nationality => 'Chilean', :include_in_selection => 1)
Country.create(:code => 'CM', :name => 'Cameroon', :nationality => 'Cameroonian', :include_in_selection => 1)
Country.create(:code => 'CN', :name => 'China', :nationality => 'Chinese', :include_in_selection => 1)
Country.create(:code => 'CO', :name => 'Colombia', :nationality => 'Colombian', :include_in_selection => 1)
Country.create(:code => 'CR', :name => 'Costa Rica', :nationality => 'Costa Rican', :include_in_selection => 0)
Country.create(:code => 'CU', :name => 'Cuba', :nationality => 'Cuban', :include_in_selection => 0)
Country.create(:code => 'CV', :name => 'Cape Verde', :nationality => 'Cape Verdean', :include_in_selection => 0)
Country.create(:code => 'CX', :name => 'Christmas Island', :nationality => 'Christmas Island', :include_in_selection => 0)
Country.create(:code => 'CY', :name => 'Cyprus', :nationality => 'Cypriot', :include_in_selection => 0)
Country.create(:code => 'CZ', :name => 'Czech Republic', :nationality => 'Czech', :include_in_selection => 1)
Country.create(:code => 'DE', :name => 'Germany', :nationality => 'German', :include_in_selection => 1)
Country.create(:code => 'DJ', :name => 'Djibouti', :nationality => 'Djibouti', :include_in_selection => 0)
Country.create(:code => 'DK', :name => 'Denmark', :nationality => 'Danish', :include_in_selection => 1)
Country.create(:code => 'DM', :name => 'Dominica', :nationality => 'Dominican', :include_in_selection => 0)
Country.create(:code => 'DO', :name => 'Dominican Republic', :nationality => 'Dominican', :include_in_selection => 0)
Country.create(:code => 'DZ', :name => 'Algeria', :nationality => 'Algerian', :include_in_selection => 0)
Country.create(:code => 'EC', :name => 'Ecuador', :nationality => 'Ecuadorian', :include_in_selection => 1)
Country.create(:code => 'EE', :name => 'Estonia', :nationality => 'Estonian', :include_in_selection => 1)
Country.create(:code => 'EG', :name => 'Egypt', :nationality => 'Egyptian', :include_in_selection => 1)
Country.create(:code => 'EH', :name => 'Western Sahara', :nationality => 'Sahrawi', :include_in_selection => 0)
Country.create(:code => 'ER', :name => 'Eritrea', :nationality => 'Eritrean', :include_in_selection => 0)
Country.create(:code => 'ES', :name => 'Spain', :nationality => 'Spanish', :include_in_selection => 1)
Country.create(:code => 'ET', :name => 'Ethiopia', :nationality => 'Ethiopian', :include_in_selection => 0)
Country.create(:code => 'FI', :name => 'Finland', :nationality => 'Finnish', :include_in_selection => 1)
Country.create(:code => 'FJ', :name => 'Fiji', :nationality => 'Fijian', :include_in_selection => 0)
Country.create(:code => 'FK', :name => 'Falkland Islands (Malvinas)', :nationality => 'Falkland Island', :include_in_selection => 0)
Country.create(:code => 'FM', :name => 'Micronesia', :nationality => 'Micronesian', :include_in_selection => 0)
Country.create(:code => 'FO', :name => 'Faroe Islands', :nationality => 'Faroese', :include_in_selection => 0)
Country.create(:code => 'FR', :name => 'France', :nationality => 'French', :include_in_selection => 1)
Country.create(:code => 'GA', :name => 'Gabon', :nationality => 'Gabonese', :include_in_selection => 0)
Country.create(:code => 'UK', :name => 'United Kingdom', :nationality => 'British', :include_in_selection => 1)
Country.create(:code => 'GD', :name => 'Grenada', :nationality => 'Grenadian', :include_in_selection => 0)
Country.create(:code => 'GE', :name => 'Georgia', :nationality => 'Georgian', :include_in_selection => 0)
Country.create(:code => 'GF', :name => 'French Guiana', :nationality => 'French Guianese', :include_in_selection => 0)
Country.create(:code => 'GG', :name => 'Guernsey', :nationality => '', :include_in_selection => 0)
Country.create(:code => 'GH', :name => 'Ghana', :nationality => 'Ghanaian', :include_in_selection => 1)
Country.create(:code => 'GI', :name => 'Gibraltar', :nationality => 'Gibraltar', :include_in_selection => 0)
Country.create(:code => 'GL', :name => 'Greenland', :nationality => 'Greenlandic', :include_in_selection => 0)
Country.create(:code => 'GM', :name => 'Gambia', :nationality => 'Gambian', :include_in_selection => 0)
Country.create(:code => 'GN', :name => 'Guinea', :nationality => 'Guinean', :include_in_selection => 0)
Country.create(:code => 'GP', :name => 'Guadeloupe', :nationality => 'Guadeloupe', :include_in_selection => 0)
Country.create(:code => 'GQ', :name => 'Equatorial Guinea', :nationality => 'Equatorial Guinean', :include_in_selection => 0)
Country.create(:code => 'GR', :name => 'Greece', :nationality => 'Greek', :include_in_selection => 1)
Country.create(:code => 'GS', :name => 'South Georgia and South Sandwich Islands', :nationality => 'South Georgia Island', :include_in_selection => 0)
Country.create(:code => 'GT', :name => 'Guatemala', :nationality => 'Guatemalan', :include_in_selection => 1)
Country.create(:code => 'GU', :name => 'Guam', :nationality => 'Guamanian', :include_in_selection => 0)
Country.create(:code => 'GW', :name => 'Guinea-Bissau', :nationality => 'Guinean', :include_in_selection => 0)
Country.create(:code => 'GY', :name => 'Guyana', :nationality => 'Guyanese', :include_in_selection => 0)
Country.create(:code => 'HK', :name => 'Hong Kong', :nationality => 'Hong Kong', :include_in_selection => 1)
Country.create(:code => 'HM', :name => 'Heard Island and McDonald Islands', :nationality => '', :include_in_selection => 0)
Country.create(:code => 'HN', :name => 'Honduras', :nationality => 'Honduran', :include_in_selection => 1)
Country.create(:code => 'HR', :name => 'Croatia', :nationality => 'Croatian', :include_in_selection => 0)
Country.create(:code => 'HT', :name => 'Haiti', :nationality => 'Hatian', :include_in_selection => 0)
Country.create(:code => 'HU', :name => 'Hungary', :nationality => 'Hungarian', :include_in_selection => 0)
Country.create(:code => 'ID', :name => 'Indonesia', :nationality => 'Indonesian', :include_in_selection => 0)
Country.create(:code => 'IE', :name => 'Ireland (Republic)', :nationality => 'Irish', :include_in_selection => 1)
Country.create(:code => 'IL', :name => 'Israel', :nationality => 'Israeli', :include_in_selection => 0)
Country.create(:code => 'IM', :name => 'Isle of Man', :nationality => 'Manx', :include_in_selection => 0)
Country.create(:code => 'IN', :name => 'India', :nationality => 'Indian', :include_in_selection => 1)
Country.create(:code => 'IO', :name => 'British Indian Ocean Territory', :nationality => 'British', :include_in_selection => 0)
Country.create(:code => 'IQ', :name => 'Iraq', :nationality => 'Iraqi', :include_in_selection => 0)
Country.create(:code => 'IR', :name => 'Iran', :nationality => 'Iranian', :include_in_selection => 0)
Country.create(:code => 'IS', :name => 'Iceland', :nationality => 'Icelandic', :include_in_selection => 0)
Country.create(:code => 'IT', :name => 'Italy', :nationality => 'Italian', :include_in_selection => 1)
Country.create(:code => 'JE', :name => 'Jersey', :nationality => '', :include_in_selection => 0)
Country.create(:code => 'JM', :name => 'Jamaica', :nationality => 'Jamaican', :include_in_selection => 0)
Country.create(:code => 'JO', :name => 'Jordan', :nationality => 'Jordanian', :include_in_selection => 0)
Country.create(:code => 'JP', :name => 'Japan', :nationality => 'Japanese', :include_in_selection => 0)
Country.create(:code => 'KE', :name => 'Kenya', :nationality => 'Kenyan', :include_in_selection => 1)
Country.create(:code => 'KG', :name => 'Kyrgyzstan', :nationality => 'Kyrgyz', :include_in_selection => 0)
Country.create(:code => 'KH', :name => 'Cambodia', :nationality => 'Cambodian', :include_in_selection => 0)
Country.create(:code => 'KI', :name => 'Kiribati', :nationality => 'Kiribati', :include_in_selection => 0)
Country.create(:code => 'KM', :name => 'Comoros', :nationality => 'Comorian', :include_in_selection => 0)
Country.create(:code => 'KN', :name => 'Saint Kitts and Nevis', :nationality => 'Kittinian/Nevisian', :include_in_selection => 0)
Country.create(:code => 'KO', :name => 'South Korea', :nationality => 'Korean', :include_in_selection => 1)
Country.create(:code => 'KW', :name => 'Kuwait', :nationality => 'Kuwaiti', :include_in_selection => 0)
Country.create(:code => 'KY', :name => 'Cayman Islands', :nationality => 'Cayman Island', :include_in_selection => 0)
Country.create(:code => 'KZ', :name => 'Kazakhstan', :nationality => 'Kazakh', :include_in_selection => 0)
Country.create(:code => 'LA', :name => 'Laos', :nationality => 'Laotian', :include_in_selection => 0)
Country.create(:code => 'LB', :name => 'Lebanon', :nationality => 'Lebanese', :include_in_selection => 1)
Country.create(:code => 'LC', :name => 'Saint Lucia', :nationality => 'Saint Lucian', :include_in_selection => 0)
Country.create(:code => 'LI', :name => 'Liechtenstein', :nationality => 'Liechtenstein', :include_in_selection => 0)
Country.create(:code => 'LK', :name => 'Sri Lanka', :nationality => 'Sri Lankan', :include_in_selection => 1)
Country.create(:code => 'LR', :name => 'Liberia', :nationality => 'Liberian', :include_in_selection => 1)
Country.create(:code => 'LS', :name => 'Lesotho', :nationality => 'Basotho (Lesostho)', :include_in_selection => 0)
Country.create(:code => 'LT', :name => 'Lithuania', :nationality => 'Lithuanian', :include_in_selection => 1)
Country.create(:code => 'LU', :name => 'Luxembourg', :nationality => 'Luxembourg', :include_in_selection => 1)
Country.create(:code => 'LV', :name => 'Latvia', :nationality => 'Latvian', :include_in_selection => 1)
Country.create(:code => 'LY', :name => 'Libya', :nationality => 'Libyan', :include_in_selection => 0)
Country.create(:code => 'MA', :name => 'Morocco', :nationality => 'Moroccan', :include_in_selection => 0)
Country.create(:code => 'MC', :name => 'Monaco', :nationality => 'Monacan', :include_in_selection => 0)
Country.create(:code => 'MD', :name => 'Moldova', :nationality => 'Moldovan', :include_in_selection => 0)
Country.create(:code => 'ME', :name => 'Montenegro', :nationality => 'Montenegrin', :include_in_selection => 0)
Country.create(:code => 'MF', :name => 'Saint Martin', :nationality => '', :include_in_selection => 0)
Country.create(:code => 'MG', :name => 'Madagascar', :nationality => 'Malagasy', :include_in_selection => 0)
Country.create(:code => 'MH', :name => 'Marshall Islands', :nationality => 'Marshall Island', :include_in_selection => 0)
Country.create(:code => 'MK', :name => 'Macedonia', :nationality => 'Macedonian', :include_in_selection => 0)
Country.create(:code => 'ML', :name => 'Mali', :nationality => 'Malian', :include_in_selection => 0)
Country.create(:code => 'MM', :name => 'Myanmar', :nationality => 'Burmese', :include_in_selection => 0)
Country.create(:code => 'MN', :name => 'Mongolia', :nationality => 'Mongolian', :include_in_selection => 0)
Country.create(:code => 'MO', :name => 'Macao', :nationality => 'Chinese', :include_in_selection => 0)
Country.create(:code => 'MP', :name => 'Northern Mariana Islands', :nationality => 'Northern Marianan', :include_in_selection => 0)
Country.create(:code => 'MQ', :name => 'Martinique', :nationality => 'Martinican', :include_in_selection => 0)
Country.create(:code => 'MR', :name => 'Mauritania', :nationality => 'Mauritanian', :include_in_selection => 0)
Country.create(:code => 'MS', :name => 'Montserrat', :nationality => 'Montserratian', :include_in_selection => 0)
Country.create(:code => 'MT', :name => 'Malta', :nationality => 'Maltese', :include_in_selection => 0)
Country.create(:code => 'MU', :name => 'Mauritius', :nationality => 'Mauritian', :include_in_selection => 0)
Country.create(:code => 'MV', :name => 'Maldives', :nationality => 'Maldivian', :include_in_selection => 0)
Country.create(:code => 'MW', :name => 'Malawi', :nationality => 'Malawian', :include_in_selection => 0)
Country.create(:code => 'MX', :name => 'Mexico', :nationality => 'Mexican', :include_in_selection => 1)
Country.create(:code => 'MY', :name => 'Malaysia', :nationality => 'Malaysian', :include_in_selection => 1)
Country.create(:code => 'MZ', :name => 'Mozambique', :nationality => 'Mozambican', :include_in_selection => 0)
Country.create(:code => 'NA', :name => 'Namibia', :nationality => 'Namibian', :include_in_selection => 0)
Country.create(:code => 'NC', :name => 'New Caledonia', :nationality => 'New Caledonian', :include_in_selection => 0)
Country.create(:code => 'NE', :name => 'Niger', :nationality => 'Nigerien', :include_in_selection => 1)
Country.create(:code => 'NF', :name => 'Norfolk Island', :nationality => 'Norfolk Island', :include_in_selection => 0)
Country.create(:code => 'NG', :name => 'Nigeria', :nationality => 'Nigerian', :include_in_selection => 1)
Country.create(:code => 'NI', :name => 'Nicaragua', :nationality => 'Nicaraguan', :include_in_selection => 0)
Country.create(:code => 'NL', :name => 'Netherlands', :nationality => 'Dutch', :include_in_selection => 1)
Country.create(:code => 'NO', :name => 'Norway', :nationality => 'Norwegian', :include_in_selection => 1)
Country.create(:code => 'NP', :name => 'Nepal', :nationality => 'Nepalese', :include_in_selection => 1)
Country.create(:code => 'NR', :name => 'Nauru', :nationality => 'Nauruan', :include_in_selection => 0)
Country.create(:code => 'NU', :name => 'Niue', :nationality => 'Niuean', :include_in_selection => 0)
Country.create(:code => 'NZ', :name => 'New Zealand', :nationality => 'New Zealand', :include_in_selection => 1)
Country.create(:code => 'OM', :name => 'Oman', :nationality => 'Omani', :include_in_selection => 0)
Country.create(:code => 'PA', :name => 'Panama', :nationality => 'Panamanian', :include_in_selection => 1)
Country.create(:code => 'PE', :name => 'Peru', :nationality => 'Peruvian', :include_in_selection => 0)
Country.create(:code => 'PF', :name => 'French Polynesia', :nationality => 'French Polynesian', :include_in_selection => 0)
Country.create(:code => 'PG', :name => 'Papua New Guinea', :nationality => 'Papua New Guinean', :include_in_selection => 1)
Country.create(:code => 'PH', :name => 'Philippines', :nationality => 'Filipino', :include_in_selection => 1)
Country.create(:code => 'PK', :name => 'Pakistan', :nationality => 'Pakistani', :include_in_selection => 0)
Country.create(:code => 'PL', :name => 'Poland', :nationality => 'Polish', :include_in_selection => 1)
Country.create(:code => 'PM', :name => 'Saint Pierre and Miquelon', :nationality => 'Saint-Pierrais', :include_in_selection => 0)
Country.create(:code => 'PN', :name => 'Pitcairn Island', :nationality => 'Pitcairn Island', :include_in_selection => 0)
Country.create(:code => 'PR', :name => 'Puerto Rico', :nationality => 'Puerto Rican', :include_in_selection => 0)
Country.create(:code => 'PS', :name => 'Palestine', :nationality => 'Palestinian', :include_in_selection => 0)
Country.create(:code => 'PT', :name => 'Portugal', :nationality => 'Portuguese', :include_in_selection => 1)
Country.create(:code => 'PW', :name => 'Palau', :nationality => 'Paluan', :include_in_selection => 0)
Country.create(:code => 'PY', :name => 'Paraguay', :nationality => 'Paraguayan', :include_in_selection => 0)
Country.create(:code => 'QA', :name => 'Qatar', :nationality => 'Qatari', :include_in_selection => 0)
Country.create(:code => 'RE', :name => 'Réunion', :nationality => 'Réunionese', :include_in_selection => 0)
Country.create(:code => 'RO', :name => 'Romania', :nationality => 'Romanian', :include_in_selection => 0)
Country.create(:code => 'RS', :name => 'Serbia', :nationality => 'Serbian', :include_in_selection => 1)
Country.create(:code => 'RU', :name => 'Russia', :nationality => 'Russian', :include_in_selection => 1)
Country.create(:code => 'RW', :name => 'Rwanda', :nationality => 'Rwandan', :include_in_selection => 0)
Country.create(:code => 'SA', :name => 'Saudi Arabia', :nationality => 'Saudi Arabian', :include_in_selection => 0)
Country.create(:code => 'SB', :name => 'Solomon Islands', :nationality => 'Solomon Island', :include_in_selection => 0)
Country.create(:code => 'SC', :name => 'Seychelles', :nationality => 'Seychellois', :include_in_selection => 0)
Country.create(:code => 'SD', :name => 'Sudan', :nationality => 'Sudanese', :include_in_selection => 0)
Country.create(:code => 'SE', :name => 'Sweden', :nationality => 'Swedish', :include_in_selection => 1)
Country.create(:code => 'SG', :name => 'Singapore', :nationality => 'Singaporean', :include_in_selection => 1)
Country.create(:code => 'SH', :name => 'Saint Helena, Ascension and Tristan da Cunha', :nationality => 'Saint Helenian', :include_in_selection => 0)
Country.create(:code => 'SI', :name => 'Slovenia', :nationality => 'Slovenian', :include_in_selection => 0)
Country.create(:code => 'SJ', :name => 'Svalbard and Jan Mayen', :nationality => '', :include_in_selection => 0)
Country.create(:code => 'SL', :name => 'Sierra Leone', :nationality => 'Sierra Leonean', :include_in_selection => 0)
Country.create(:code => 'SM', :name => 'San Marino', :nationality => 'Sammarinese', :include_in_selection => 0)
Country.create(:code => 'SN', :name => 'Senegal', :nationality => 'Senegalese', :include_in_selection => 0)
Country.create(:code => 'SO', :name => 'Somalia', :nationality => 'Somali', :include_in_selection => 0)
Country.create(:code => 'SR', :name => 'Suriname', :nationality => 'Surinamese', :include_in_selection => 0)
Country.create(:code => 'ST', :name => 'SÃ£o TomÃ© and PrÃ­ncipe', :nationality => 'SÃ£o TomÃ©an', :include_in_selection => 0)
Country.create(:code => 'SV', :name => 'El Salvador', :nationality => 'El Salvadoran', :include_in_selection => 1)
Country.create(:code => 'SY', :name => 'Syria', :nationality => 'Syrian', :include_in_selection => 0)
Country.create(:code => 'SZ', :name => 'Swaziland', :nationality => 'Swazi', :include_in_selection => 0)
Country.create(:code => 'TC', :name => 'Turks and Caicos Islands', :nationality => 'Turks and Caicos Island', :include_in_selection => 0)
Country.create(:code => 'TD', :name => 'Chad', :nationality => 'Chadian', :include_in_selection => 0)
Country.create(:code => 'TF', :name => 'French Southern Territories', :nationality => '', :include_in_selection => 0)
Country.create(:code => 'TG', :name => 'Togo', :nationality => 'Togolese', :include_in_selection => 1)
Country.create(:code => 'TH', :name => 'Thailand', :nationality => 'Thai', :include_in_selection => 1)
Country.create(:code => 'TJ', :name => 'Tajikistan', :nationality => 'Tajikistani', :include_in_selection => 0)
Country.create(:code => 'TK', :name => 'Tokelau', :nationality => '', :include_in_selection => 0)
Country.create(:code => 'TL', :name => 'Timor-Leste', :nationality => 'Timorese', :include_in_selection => 0)
Country.create(:code => 'TM', :name => 'Turkmenistan', :nationality => 'Turkeman', :include_in_selection => 0)
Country.create(:code => 'TN', :name => 'Tunisia', :nationality => 'Tunisian', :include_in_selection => 0)
Country.create(:code => 'TO', :name => 'Tonga', :nationality => 'Tongan', :include_in_selection => 0)
Country.create(:code => 'TR', :name => 'Turkey', :nationality => 'Turkish', :include_in_selection => 0)
Country.create(:code => 'TT', :name => 'Trinidad and Tobago', :nationality => 'Trinidadian', :include_in_selection => 0)
Country.create(:code => 'TV', :name => 'Tuvalu', :nationality => 'Tuvaluan', :include_in_selection => 0)
Country.create(:code => 'TW', :name => 'Taiwan', :nationality => 'Taiwanese', :include_in_selection => 1)
Country.create(:code => 'TZ', :name => 'Tanzania', :nationality => 'Tanzanian', :include_in_selection => 0)
Country.create(:code => 'UA', :name => 'Ukraine', :nationality => 'Ukrainian', :include_in_selection => 1)
Country.create(:code => 'UG', :name => 'Uganda', :nationality => 'Ugandan', :include_in_selection => 0)
Country.create(:code => 'UM', :name => 'United States minor outlying islands', :nationality => 'American', :include_in_selection => 0)
Country.create(:code => 'US', :name => 'United States', :nationality => 'American', :include_in_selection => 1)
Country.create(:code => 'UY', :name => 'Uruguay', :nationality => 'Uruguayan', :include_in_selection => 0)
Country.create(:code => 'UZ', :name => 'Uzbekistan', :nationality => 'Uzbek', :include_in_selection => 0)
Country.create(:code => 'VA', :name => 'Vatican', :nationality => 'Vatican', :include_in_selection => 0)
Country.create(:code => 'VC', :name => 'Saint Vincent and the Grenadines', :nationality => 'St. Vincentian', :include_in_selection => 0)
Country.create(:code => 'VE', :name => 'Venezuela', :nationality => 'Venezuelan', :include_in_selection => 1)
Country.create(:code => 'VG', :name => 'British Virgin Islands', :nationality => 'British Virgin Island', :include_in_selection => 1)
Country.create(:code => 'VI', :name => 'American Virgin Islands', :nationality => 'American Virgin Island', :include_in_selection => 1)
Country.create(:code => 'VN', :name => 'Vietnam', :nationality => 'Vietnamese', :include_in_selection => 0)
Country.create(:code => 'VU', :name => 'Vanuatu', :nationality => 'Vanuatuan', :include_in_selection => 0)
Country.create(:code => 'WF', :name => 'Wallis and Futuna', :nationality => 'Wallisian/Futunan', :include_in_selection => 0)
Country.create(:code => 'WS', :name => 'Samoa', :nationality => 'Samoan', :include_in_selection => 0)
Country.create(:code => 'YE', :name => 'Yemen', :nationality => 'Yemeni', :include_in_selection => 0)
Country.create(:code => 'YT', :name => 'Mayotte', :nationality => 'Mahoran', :include_in_selection => 0)
Country.create(:code => 'ZA', :name => 'South Africa', :nationality => 'South African', :include_in_selection => 1)
Country.create(:code => 'ZM', :name => 'Zambia', :nationality => 'Zambian', :include_in_selection => 0)
Country.create(:code => 'ZW', :name => 'Zimbabwe', :nationality => 'Zimbabwean', :include_in_selection => 0)
Country.create(:code => 'UKI', :name => 'Northern Ireland', :nationality => 'Northern Irish', :include_in_selection => 1)
Country.create(:code => 'UKS', :name => 'Scotland', :nationality => 'Scottish', :include_in_selection => 1)
Country.create(:code => 'UKW', :name => 'Wales', :nationality => 'Welsh', :include_in_selection => 1)
Country.create(:code => 'XT', :name => 'Tésàㅯ', :nationality => 'Test2', :include_in_selection => 0)
Country.create(:code => '??', :name => 'Not known', :nationality => 'Not known', :include_in_selection => 1)

Education.delete_all
Education.create(:description => 'Some school', :code => 10)
Education.create(:description => 'High school grad', :code => 20)
Education.create(:description => 'Some college', :code => 30)
Education.create(:description => 'Some Bible college', :code => 31)
Education.create(:description => 'Certificate course', :code => 35)
Education.create(:description => '2 yr college', :code => 40)
Education.create(:description => '2 yr Bible college', :code => 41)
Education.create(:description => '2 yr nursing degree', :code => 45)
Education.create(:description => '4 yr college', :code => 50)
Education.create(:description => 'Masters level', :code => 60)
Education.create(:description => 'Doctoral level', :code => 70)
Education.create(:description => 'xts', :code => 995)
Education.create(:description => 'unspecified', :code => 99)

EmploymentStatus.delete_all
EmploymentStatus.create(:description => 'Adult-MK', :code => 'MKA')
EmploymentStatus.create(:description => 'Career-Affiliate', :code => 'CAF')
EmploymentStatus.create(:description => 'Recruited by ECWA-Affiliate', :code => 'ECA')
EmploymentStatus.create(:description => 'Recruited by ECWA', :code => 'ECW')
EmploymentStatus.create(:description => 'Career - Field Staff', :code => 'CAR')
EmploymentStatus.create(:description => 'MK dependent', :code => 'MKD')
EmploymentStatus.create(:description => 'ST-Affiliate', :code => 'STF')
EmploymentStatus.create(:description => 'Special Assignment', :code => 'SPC')
EmploymentStatus.create(:description => 'Short Term Associate', :code => 'STA')
EmploymentStatus.create(:description => 'Visitor', :code => 'VIS')
EmploymentStatus.create(:description => 'unspecified', :code => '???')

Location.delete_all
Location.create(:description => 'Enugu', :city_id => City.find_by_name('Enugu').id, :code => 10101)
Location.create(:description => 'Aba Bible College', :city_id => City.find_by_name('Aba').id, :code => 10201)
Location.create(:description => 'Egbe Hospital', :city_id => City.find_by_name('Egbe').id, :code => 20101)
Location.create(:description => 'Igbaja Seminary', :city_id => City.find_by_name('Igbaja').id, :code => 20201)
Location.create(:description => 'Ilorin', :city_id => City.find_by_name('Ilorin').id, :code => 20300)
Location.create(:description => 'Kaiama', :city_id => City.find_by_name('Kaiama').id, :code => 20400)
Location.create(:description => 'Abuja', :city_id => City.find_by_name('Abuja').id, :code => 30000)
Location.create(:description => 'Baptist Guest House Abuja', :city_id => City.find_by_name('Abuja').id, :code => 30001)
Location.create(:description => 'Gure', :city_id => City.find_by_name('Gure').id, :code => 30201)
Location.create(:description => 'Kagoro', :city_id => City.find_by_name('Kagoro').id, :code => 30300)
Location.create(:description => 'Kagoro -- Seminary', :city_id => City.find_by_name('Kagoro').id, :code => 30301)
Location.create(:description => 'Adunu/ECWA/EMS', :city_id => City.find_by_name('Adunu').id, :code => 30400)
Location.create(:description => 'Samaru/ECWA Widows Sch', :city_id => City.find_by_name('Samaru').id, :code => 30401)
Location.create(:description => 'Minna', :city_id => City.find_by_name('Minna').id, :code => 30500)
Location.create(:description => 'Ningi', :city_id => City.find_by_name('Ningi').id, :code => 40201)
Location.create(:description => 'Billiri -- ECWA Theol College', :city_id => City.find_by_name('Billiri').id, :code => 40500)
Location.create(:description => 'Kano', :city_id => City.find_by_name('Kano').id, :code => 50101)
Location.create(:description => 'Tofa/ECWA Bible Train. Sch.', :city_id => City.find_by_name('Tofa').id, :code => 50201)
Location.create(:description => 'Jos', :city_id => City.find_by_name('Jos').id, :code => 60100)
Location.create(:description => 'BUTH (Evangel) Hospital', :city_id => City.find_by_name('Jos').id, :code => 60101)
Location.create(:description => 'Spring of Life', :city_id => City.find_by_name('Jos').id, :code => 60102)
Location.create(:description => 'Gidan Bege', :city_id => City.find_by_name('Jos').id, :code => 60105)
Location.create(:description => 'Challenge Compound', :city_id => City.find_by_name('Jos').id, :code => 60110)
Location.create(:description => 'Jos Pharmacy Compound', :city_id => City.find_by_name('Jos').id, :code => 60111)
Location.create(:description => 'Jos ECWA/SIM Headquarters', :city_id => City.find_by_name('Jos').id, :code => 60112)
Location.create(:description => 'Jos Oasis Campound', :city_id => City.find_by_name('Jos').id, :code => 60120)
Location.create(:description => 'Niger Creek Compound', :city_id => City.find_by_name('Jos').id, :code => 60121)
Location.create(:description => 'Apollo Crescent', :city_id => City.find_by_name('Jos').id, :code => 60122)
Location.create(:description => 'Woyke House', :city_id => City.find_by_name('Jos').id, :code => 60123)
Location.create(:description => 'Danish Lutheran Compound', :city_id => City.find_by_name('Jos').id, :code => 60125)
Location.create(:description => 'Hillcrest School', :city_id => City.find_by_name('Jos').id, :code => 60126)
Location.create(:description => 'Jos CRC Mountain View', :city_id => City.find_by_name('Jos').id, :code => 60127)
Location.create(:description => 'Jos ELM House', :city_id => City.find_by_name('Jos').id, :code => 60128)
Location.create(:description => 'JETS', :city_id => City.find_by_name('Jos').id, :code => 60180)
Location.create(:description => 'Word of  Life', :city_id => City.find_by_name('Jos').id, :code => 60190)
Location.create(:description => 'Jos City Ministries', :city_id => City.find_by_name('Jos').id, :code => 60192)
Location.create(:description => 'Miango', :city_id => City.find_by_name('Miango').id, :code => 60200)
Location.create(:description => 'Miango MRH', :city_id => City.find_by_name('Miango').id, :code => 60201)
Location.create(:description => 'Miango Kent Academy', :city_id => City.find_by_name('Miango').id, :code => 60202)
Location.create(:description => 'Miango Dental Clinic', :city_id => City.find_by_name('Miango').id, :code => 60203)
Location.create(:description => 'unspecified', :city_id => City.find_by_name('unspecified').id, :code => 0)

Ministry.delete_all
Ministry.create(:description => 'Evangelism personnel', :code => 110)
Ministry.create(:description => 'BSF teaching leader', :code => 210)
Ministry.create(:description => 'Discipleship', :code => 220)
Ministry.create(:description => 'Discipleship (pastoral training)', :code => 222)
Ministry.create(:description => 'Theological educator', :code => 230)
Ministry.create(:description => 'Theological services translator', :code => 239)
Ministry.create(:description => "Children\'s ministry", :code => 250)
Ministry.create(:description => 'Sports ministry', :code => 260)
Ministry.create(:description => 'Youth camp ministry', :code => 270)
Ministry.create(:description => 'Community worker', :code => 300)
Ministry.create(:description => 'City Ministries', :code => 310)
Ministry.create(:description => 'Urban youth ministry', :code => 311)
Ministry.create(:description => 'Rural development worker', :code => 330)
Ministry.create(:description => 'Physician', :code => 400)
Ministry.create(:description => 'Psychiatrist', :code => 405)
Ministry.create(:description => 'Family practice/GP', :code => 410)
Ministry.create(:description => 'Internal medicine', :code => 415)
Ministry.create(:description => 'Internal medicine/pediatrics', :code => 416)
Ministry.create(:description => 'Pediatrician', :code => 420)
Ministry.create(:description => 'Surgeon', :code => 430)
Ministry.create(:description => 'Orthopedic surgeon', :code => 431)
Ministry.create(:description => 'ENT', :code => 435)
Ministry.create(:description => 'Ob/Gyn', :code => 440)
Ministry.create(:description => 'Ob/Gyn (VVF)', :code => 441)
Ministry.create(:description => 'Ophthalmologist', :code => 445)
Ministry.create(:description => 'Nurse midwife', :code => 452)
Ministry.create(:description => 'Nurse educator', :code => 455)
Ministry.create(:description => 'Nurse specialist', :code => 456)
Ministry.create(:description => 'Dentist', :code => 460)
Ministry.create(:description => 'Health educator', :code => 480)
Ministry.create(:description => 'Allied health professionals', :code => 490)
Ministry.create(:description => 'Biomedical eng.', :code => 491)
Ministry.create(:description => 'Medical elective', :code => 492)
Ministry.create(:description => 'Medical elective--Resident', :code => 493)
Ministry.create(:description => 'Medical unspecified', :code => 499)
Ministry.create(:description => 'Missionary services', :code => 500)
Ministry.create(:description => 'Administrator', :code => 510)
Ministry.create(:description => 'Financial manager', :code => 515)
Ministry.create(:description => 'Service manager', :code => 520)
Ministry.create(:description => 'Travel services', :code => 530)
Ministry.create(:description => 'Staff development', :code => 550)
Ministry.create(:description => 'Missionary child care', :code => 590)
Ministry.create(:description => 'Manager (Oasis)', :code => 591)
Ministry.create(:description => 'Hostel parent', :code => 592)
Ministry.create(:description => 'Student teacher', :code => 605)
Ministry.create(:description => 'School teacher', :code => 610)
Ministry.create(:description => 'Teacher/chaplain', :code => 615)
Ministry.create(:description => 'MK youth pastor', :code => 620)
Ministry.create(:description => 'Housewife/home schooling', :code => 690)
Ministry.create(:description => 'Technical', :code => 700)
Ministry.create(:description => 'Accompanying spouse', :code => 900)
Ministry.create(:description => 'Rural minstry', :code => 910)
Ministry.create(:description => 'STA', :code => 920)
Ministry.create(:description => 'Visitor', :code => 1010)
Ministry.create(:description => 'MK', :code => 9000)
Ministry.create(:description => 'Navigators', :code => 221)
Ministry.create(:description => 'Unspecified', :code => 9999)

State.delete_all
State.create(:name => 'Abia', :zone => '')
State.create(:name => 'Adamawa', :zone => '')
State.create(:name => 'Akwa Ibom', :zone => '')
State.create(:name => 'Anambra', :zone => '')
State.create(:name => 'Bauchi', :zone => '')
State.create(:name => 'Bayelsa', :zone => '')
State.create(:name => 'Benue', :zone => '')
State.create(:name => 'Borno', :zone => '')
State.create(:name => 'Cross River', :zone => '')
State.create(:name => 'Delta', :zone => '')
State.create(:name => 'Ebonyi', :zone => '')
State.create(:name => 'Edo', :zone => '')
State.create(:name => 'Ekiti', :zone => '')
State.create(:name => 'Gombe', :zone => '')
State.create(:name => 'Imo', :zone => '')
State.create(:name => 'Jigawa', :zone => '')
State.create(:name => 'Kaduna', :zone => '')
State.create(:name => 'Kano', :zone => '')
State.create(:name => 'Katsina', :zone => '')
State.create(:name => 'Kebbi', :zone => '')
State.create(:name => 'Kogi', :zone => '')
State.create(:name => 'Kwara', :zone => '')
State.create(:name => 'Lagos', :zone => '')
State.create(:name => 'Nasarawa', :zone => '')
State.create(:name => 'Niger', :zone => '')
State.create(:name => 'Ogun', :zone => '')
State.create(:name => 'Ondo', :zone => '')
State.create(:name => 'Osun', :zone => '')
State.create(:name => 'Oyo', :zone => '')
State.create(:name => 'Plateau', :zone => '')
State.create(:name => 'Rivers', :zone => '')
State.create(:name => 'Sokoto', :zone => '')
State.create(:name => 'Taraba', :zone => '')
State.create(:name => 'Yobe', :zone => '')
State.create(:name => 'Zamfara', :zone => '')
State.create(:name => 'Abuja FCT', :zone => '')

Status.delete_all
Status.create(:description => 'Alumni', :code => 'A', :active => '', :on_field => '')
Status.create(:description => 'On field w parents', :code => 'C', :active => 1, :on_field => 1)
Status.create(:description => 'On the field', :code => 'F', :active => 1, :on_field => 1)
Status.create(:description => 'College', :code => 'G', :active => '', :on_field => '')
Status.create(:description => 'Home assignment', :code => 'H', :active => 1, :on_field => '')
Status.create(:description => 'On leave', :code => 'L', :active => '', :on_field => '')
Status.create(:description => 'Adult MK', :code => 'M', :active => '', :on_field => '')
Status.create(:description => 'Alumni-Retired', :code => 'R', :active => '', :on_field => '')
Status.create(:description => 'Not specified', :code => 'Z', :active => '', :on_field => '')
Status.create(:description => 'With the Lord!', :code => '@', :active => 0, :on_field => 0)
Status.create(:description => 'Pipeline', :code => 'P', :active => '', :on_field => '')
Status.create(:description => 'Alumni MK', :code => 'B', :active => 0, :on_field => 0)
