require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MessagesController do

      before(:each) do
        @user = Factory(:user, :admin=>true)
        test_sign_in(@user)
      end

  def mock_message(stubs={})
    @mock_message ||= mock_model(Message, stubs).as_null_object
  end

  describe 'New' do
    
    it 'sets defaults from Settings' do
      put :new
      settings_with_default = [:confirm_time_limit, :retries, :retry_interval, :expiration, 
                               :response_time_limit, :importance]
      settings_with_default.each {|setting| assigns(:record)[setting].should == Settings.messages[setting]}
    end
  end

  describe 'Edit' do
    before(:each) do
    end
    it 'converts to_groups to array' do
      message = Message.create(:to_groups=>"1,2", :body=>"Test")
#      Message.stub(:find).with(1).and_return(message)
      put :edit, :id=>message.id
      assigns(:record).to_groups.should == [1, 2]
    end
  end
  
  describe 'Create' do
    it 'adds user name to record' do
      message = Message.new(:to_groups=>"1,2", :body=>"Test")
#      Message.stub(:save).and_return(true)
      post :create, :record => {:body=>"test", :to_groups=>["1", '2']}
      Message.first.user.should == @user
    end
  end
  
      

end
