require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PersTasksController do

  def mock_pers_task(stubs={})
    @mock_pers_task ||= mock_model(PersTask, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all pers_tasks as @pers_tasks" do
      PersTask.stub(:all) { [mock_pers_task] }
      get :index
      assigns(:pers_tasks).should eq([mock_pers_task])
    end
  end

  describe "GET show" do
    it "assigns the requested pers_task as @pers_task" do
      PersTask.stub(:find).with("37") { mock_pers_task }
      get :show, :id => "37"
      assigns(:pers_task).should be(mock_pers_task)
    end
  end

  describe "GET new" do
    it "assigns a new pers_task as @pers_task" do
      PersTask.stub(:new) { mock_pers_task }
      get :new
      assigns(:pers_task).should be(mock_pers_task)
    end
  end

  describe "GET edit" do
    it "assigns the requested pers_task as @pers_task" do
      PersTask.stub(:find).with("37") { mock_pers_task }
      get :edit, :id => "37"
      assigns(:pers_task).should be(mock_pers_task)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created pers_task as @pers_task" do
        PersTask.stub(:new).with({'these' => 'params'}) { mock_pers_task(:save => true) }
        post :create, :pers_task => {'these' => 'params'}
        assigns(:pers_task).should be(mock_pers_task)
      end

      it "redirects to the created pers_task" do
        PersTask.stub(:new) { mock_pers_task(:save => true) }
        post :create, :pers_task => {}
        response.should redirect_to(pers_task_url(mock_pers_task))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pers_task as @pers_task" do
        PersTask.stub(:new).with({'these' => 'params'}) { mock_pers_task(:save => false) }
        post :create, :pers_task => {'these' => 'params'}
        assigns(:pers_task).should be(mock_pers_task)
      end

      it "re-renders the 'new' template" do
        PersTask.stub(:new) { mock_pers_task(:save => false) }
        post :create, :pers_task => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pers_task" do
        PersTask.stub(:find).with("37") { mock_pers_task }
        mock_pers_task.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :pers_task => {'these' => 'params'}
      end

      it "assigns the requested pers_task as @pers_task" do
        PersTask.stub(:find) { mock_pers_task(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:pers_task).should be(mock_pers_task)
      end

      it "redirects to the pers_task" do
        PersTask.stub(:find) { mock_pers_task(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(pers_task_url(mock_pers_task))
      end
    end

    describe "with invalid params" do
      it "assigns the pers_task as @pers_task" do
        PersTask.stub(:find) { mock_pers_task(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:pers_task).should be(mock_pers_task)
      end

      it "re-renders the 'edit' template" do
        PersTask.stub(:find) { mock_pers_task(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pers_task" do
      PersTask.stub(:find).with("37") { mock_pers_task }
      mock_pers_task.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the pers_tasks list" do
      PersTask.stub(:find) { mock_pers_task }
      delete :destroy, :id => "1"
      response.should redirect_to(pers_tasks_url)
    end
  end

end
