require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SentMessagesController do

  def mock_sent_message(stubs={})
    @mock_sent_message ||= mock_model(SentMessage, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all sent_messages as @sent_messages" do
      SentMessage.stub(:all) { [mock_sent_message] }
      get :index
      assigns(:sent_messages).should eq([mock_sent_message])
    end
  end

  describe "GET show" do
    it "assigns the requested sent_message as @sent_message" do
      SentMessage.stub(:find).with("37") { mock_sent_message }
      get :show, :id => "37"
      assigns(:sent_message).should be(mock_sent_message)
    end
  end

  describe "GET new" do
    it "assigns a new sent_message as @sent_message" do
      SentMessage.stub(:new) { mock_sent_message }
      get :new
      assigns(:sent_message).should be(mock_sent_message)
    end
  end

  describe "GET edit" do
    it "assigns the requested sent_message as @sent_message" do
      SentMessage.stub(:find).with("37") { mock_sent_message }
      get :edit, :id => "37"
      assigns(:sent_message).should be(mock_sent_message)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created sent_message as @sent_message" do
        SentMessage.stub(:new).with({'these' => 'params'}) { mock_sent_message(:save => true) }
        post :create, :sent_message => {'these' => 'params'}
        assigns(:sent_message).should be(mock_sent_message)
      end

      it "redirects to the created sent_message" do
        SentMessage.stub(:new) { mock_sent_message(:save => true) }
        post :create, :sent_message => {}
        response.should redirect_to(sent_message_url(mock_sent_message))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sent_message as @sent_message" do
        SentMessage.stub(:new).with({'these' => 'params'}) { mock_sent_message(:save => false) }
        post :create, :sent_message => {'these' => 'params'}
        assigns(:sent_message).should be(mock_sent_message)
      end

      it "re-renders the 'new' template" do
        SentMessage.stub(:new) { mock_sent_message(:save => false) }
        post :create, :sent_message => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sent_message" do
        SentMessage.stub(:find).with("37") { mock_sent_message }
        mock_sent_message.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :sent_message => {'these' => 'params'}
      end

      it "assigns the requested sent_message as @sent_message" do
        SentMessage.stub(:find) { mock_sent_message(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:sent_message).should be(mock_sent_message)
      end

      it "redirects to the sent_message" do
        SentMessage.stub(:find) { mock_sent_message(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(sent_message_url(mock_sent_message))
      end
    end

    describe "with invalid params" do
      it "assigns the sent_message as @sent_message" do
        SentMessage.stub(:find) { mock_sent_message(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:sent_message).should be(mock_sent_message)
      end

      it "re-renders the 'edit' template" do
        SentMessage.stub(:find) { mock_sent_message(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sent_message" do
      SentMessage.stub(:find).with("37") { mock_sent_message }
      mock_sent_message.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the sent_messages list" do
      SentMessage.stub(:find) { mock_sent_message }
      delete :destroy, :id => "1"
      response.should redirect_to(sent_messages_url)
    end
  end

end
